config/routes.rb
Rails.application.routes.draw do

  resources :reviews

  root 'movies#index'

  get 'movies'=>'movies#index'
  post 'movies'=>'movies#index'
  get 'movies'=>'movies#get_movies'

  get 'movies/:id'=>"movies#show"

end

app/models/review.rb
class Review < ActiveRecord::Base
  validates :user_email, :presence => true
  validates_format_of :user_email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

  validates :rating, :presence => true

  def self.get_average_for_movie(id)
  	reviews = Review.where(:movie_id=>id)
  	if reviews.size==0
  		return 0
  	else
  		values = reviews.collect{|x| x["rating"]}
  		puts values
  		return values.reduce(:+)/reviews.size
  	end 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

	def index
		Tmdb::Api.key("37f65bf08da3e2a621b7e23dbb2fe510")
		begin
			@movies = Tmdb::Movie.popular
			if params[:title]
				@search = Tmdb::Search.new
				@search.resource('movie') # determines type of resource
				@search.query(params[:title]) # the query to search against
				@result = @search.fetch # makes request
				puts @result.inspect
				@movies = @result
			else
				case params[:sort_by]
				when 'title'
					if params[:order]=='asc'
						@movies = @movies.sort_by { |x| x["title"] }
					else
						@movies = @movies.sort_by { |x| x["title"] }.reverse
					end
				when 'release_date'
					if params[:order]=='asc'
						@movies = @movies.sort_by { |x| x["release_date"] }
					else
						@movies = @movies.sort_by { |x| x["release_date"] }.reverse
					end
				when 'genre'
					@res_movies=[]
					@movies.each  do |movie|
						genres = Tmdb::Movie.detail(movie["id"])["genres"].collect{|x| x["name"]}.inspect
						if genres.include? params[:order]
							@res_movies<<movie
						end
					end
					@movies=@res_movies
				end
	  	end
	  rescue SocketError =>e
	  	puts e.inspect
	  	@movies=[]
		end
		
		begin
			@genres = Tmdb::Genre.list["genres"]
		rescue SocketError =>e
			puts e.inspect
			@genres=[]
		end
		respond_to do |format|
				format.js
        format.html 
    end
	end

	def show
		@movie=Tmdb::Movie.detail(params[:id])
		@reviews = Review.where(movie_id:params[:id])
	end
	
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.js
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.js
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:movie_id, :user_email, :rating, :comment,:movie_title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">

          <a href="../" class="navbar-brand">Poopcorn Time <span class="label label-default">nightly</span> 
          </a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
             <li><a href="/"> Home </a> </li>
             <li><a href="/reviews"> <i class="fa fa-book"></i>Read All Reviews</a> </li>
           </ul>
        </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Poopcorn Time | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style='padding-top:100px;'>
 <%=render 'layouts/navbar'%>

<%= yield %>
<div class="loading-container"></div>

     <div id="push" style="height: 60px;"></div><!--for sticky footer-->  
     <hr>
     <div class='footer'>
      <p>copyright 2015 | yunrui zhang</p>
    </div>
  </div>
</body>
</html>

app/views/movies/_movie.html.erb
<%=@title%>
<div id="raty"></div>



	<div class="form-group">
		<%=label_tag :user_email%>
		<%=text_field_tag :user_email,nil,class:"form-control"%>
	</div>

<div id='comment-form'></div>

app/views/movies/_movies.html.erb
<%@slices = movies.each_slice(4).to_a%>
            <%@slices.each do |slice|%>
                <div class="row">
                <%slice.each do |movie|%>
                  <div class="col-md-3 portfolio-item">
                    <a href='/movies/<%=movie["id"]%>'>
                        <img class="img-rounded img-responsive img-border-bottom photo" src="http://image.tmdb.org/t/p/w154/<%=movie['poster_path']%>"/>
                    </a>
                    <h5 class="tool-title">
                      <a href='#'><%=movie["title"]%></a><br>
                    </h5>
                    <p><%=movie["release_date"]%></p>
                  </div>
                <%end%>
                </div>
            <%end%>
          </div>

app/views/movies/get_movies.js.erb
$('#result').html("<%=j render partial:'movie'%>");

$('#raty').raty({
    path:"/assets",
    hints: ['Very Bad', 'Poor', 'Average', 'Good', 'Excellent'],
    click: function(score, evt) {
        var email = $('#user_email').val();
        if (!email){
          alert("Please input an email!");
          return false;
        }
        $.ajax({
          url: '/reviews/',
          type: 'POST',
          data: { "review":
                  {
                    "rating": score,
                    "imdbID":'<%=@imdb_id%>',
                    "user_email":email
                  } 
                }, 
          success:function(data){
              alert("Rated!");
              console.log(data);
          }
        });//end of ajax
    }//end of click
});

app/views/movies/index.html.erb
<% content_for :title, "Home" %>
<div class="container ">
    <div class="row">
        <div class="col-lg-1 col-md-1"></div>
        <div class="col-lg-10 col-md-10">
            <h1>Popular Movies (<%=@movies.size%>)</h1>

            <ul class="nav nav-pills">
                <li role="presentation">
                   <%=button_to 'All Popular','/' ,class:"btn btn-default",method: :get%>
                </li>
                <li role="presentation">
                    <div class="btn-group">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">Sort By Title <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <li class='show-loading'><%= link_to "A-Z", :controller => "movies", :action => "index", :sort_by => "title",:order=>"asc" ,remote:true%></li>
                            <li class='show-loading'><%= link_to "Z-A", :controller => "movies", :action => "index", :sort_by => "title",:order=>"dec",remote:true%></li>
                        </ul>
                    </div>
                </li>
                <li role="presentation">
                    <div class="btn-group">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">Sort By Release Date <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <li class='show-loading'><%= link_to "Earlier!", :controller => "movies", :action => "index", :sort_by => "release_date",:order=>"asc" ,remote:true%></li>
                            <li class='show-loading'><%= link_to "Later", :controller => "movies", :action => "index", :sort_by => "release_date",:order=>"dec",remote:true %></li>
                        </ul>
                    </div>
                </li>
                <li role="presentation">
                    <div class="btn-group">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">Sort Genre <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <%@genres.each do |genre|%>
                            <li class='show-loading'><%= link_to genre["name"], :controller => "movies", :action => "index", :sort_by => "genre",:order=>genre["name"] ,remote:true%></a></li>
                            <%end%>
                        </ul>
                    </div>
                </li>
                
                    <%= form_tag('/movies/', method: "get") do %>
                        <li>
                            <div class="input-group">
                            <%= text_field_tag(:title,nil,class:"form-control") %>
                            <span class="input-group-btn show-loading">
                                <%= submit_tag("Search",class:'btn btn-default') %>
                            </span>
                        </div>
                    </li>
                    <% end %>
            </ul>
          <hr>

            <div id='movies'>
              <%=render partial:"movies",locals:{movies:@movies}%>
            </div>

         <div class="col-lg-1 col-md-1"></div>
    </div>
    <div class='row'>
        <div class="col-lg-2 col-md-2"></div>
        <div class="col-lg-8 col-md-8 " id = 'result'></div>
        <div class="col-lg-2 col-md-2"></div>
    </div>
</div>
<script type="text/javascript">
$(".show-loading > a").click(function(){
    show_loading_body();
});
$(".show-loading > input").click(function(){
    show_loading_body();
});

</script>

app/views/movies/index.js.erb
$('#movies').html('<%=j render partial:"movies",locals:{movies:@movies}%>');
hide_loading_body();

app/views/movies/show.html.erb
<% content_for :title, @movie["title"] %>

<div class="container">
    <div class="row">

        <div class="jumbotron" style="background-color:rgba(142,68,173,0.05)">
            <div class="row">
                <div class="col-md-4">
                    <img class="img-rounded img-responsive img-border-bottom photo" src="http://image.tmdb.org/t/p/w154/<%=@movie['poster_path']%>"/>
                </div>
                <div class="col-md-8">
                <h1><%=@movie["title"]%></h1>
                <h3><%=@movie["tagline"]%></h3>
                  <%if @movie["genres"]%>
                    <p>
                     Genres:
                     <%@movie["genres"].each do |genre|%>
                      <span class ="label label-default"><%=genre["name"]%></span>
                      <%end%>
                    </p>
                    <%end%>
                    <p>Release :<%=@movie["release_date"]%></p>
                    <p>Runtime :<%=@movie["runtime"]%></p>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6">
          <h3>Overview</h3>
          <p><%=@movie["overview"]%></p>

          <h3>Average PoopCorn Time Review (<%=@reviews.size%> reviews)</h3>
          <div id='average_review'></div>

          <h3>Add your review</h3>
            <div class="form-group">
              <%=label_tag 'Your email* (Required)'%>
              <%=email_field_tag :user_email,nil,class:"form-control"%>
            </div>
            <div id="raty"></div>
            <div id='comment-form'></div>
        </div>
        <div class="col-lg-6 col-md-6">
            <h2>Reviews</h2>
            <div id='reviews'>
						  <%=render @reviews%>
            </div>
					
          </div>
					</div>
				</div>

				<script type="text/javascript">

function IsEmail(email) {
  var regex = /^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/;
  return regex.test(email);
}
$('.raty').each(function(){

    var tid = $(this).attr('ref'); 
    var score  = $(this).attr('score-helper');
    console.log(tid);
    $(this).raty({
          path:"/assets",
          target : tid ,
          readOnly:  true,
          score:score,
          number:     10,
          showHalf:  true
    }); 
}); 


    $('#average_review').raty({
          path:"/assets",
          readOnly:  true,
          score: <%=Review.get_average_for_movie(@movie["id"])%>,
          number:     10,
          showHalf:  true
    });


$('#raty').raty({
    path:"/assets",
      number:     10,
    click: function(score, evt) {

        var email = $('#user_email').val();
        if (!IsEmail(email)){
          alert("Please input a valid email!");
          return false;
        }

        $.ajax({
          url: '/reviews/',
          type: 'POST',
          data: { "review":
                  {
                    "rating": score,
                    "movie_id":'<%=@movie["id"]%>',
                    "movie_title":'<%=@movie["title"]%>',
                    "user_email":email
                  } 
                }, 
          success:function(data){
              alert("Congrats! Successfully Rated!");
              console.log(data);
          }
        });//end of ajax
    }//end of click
});



</script>

app/views/reviews/_comment_form.html.erb
<%=form_for review, remote:true do |f|%>
	<div class="form-group">
		<%=f.label "Add a comment to this review (OPTIONAL)"%>
		<%=f.text_area :comment,class:"form-control"%>
	</div>
	<%=f.hidden_field :imdbID,value:@imdb_id%>
	<div class="form-group">
		<%=f.submit "Add Comment", class:'btn btn-primary'%>
		<a href='#' id='skip'>Skip</a>
	</div>
<%end%>
<script type="text/javascript">

$('#skip').click(function(){


$('#reviews').prepend('<%=j render partial:"reviews/review",locals:{review:review}%>');

$('#raty-<%=review.id%>').raty({
          path:"/assets",
          readOnly:  true,
          score:<%=@review.rating%>,
          number:     10,
          showHalf:  true
}); 

alert('OK! We have add your rating without comment');
return false;
});
</script>

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :movie_id %><br>
    <%= f.text_field :movie_id %>
  </div>
  <div class="field">
    <%= f.label :user_email %><br>
    <%= f.text_field :user_email %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/_review.html.erb
<%if review.movie_title%>
 <p>I give <a href='/movies/<%=review.movie_id%>'><%=review.movie_title%></a><p>
<%end%>
<div class='raty'  ref='#raty-<%=review.id%>' score-helper="<%=review.rating%>"></div>
<div id='raty-<%=review.id%>'></div>
by <%=review.user_email.split('@')[0]%>
<%= time_ago_in_words(review.updated_at) %> ago
<br>
<%if review.comment%>
<p>Becasue:</p>
<p><%=review.comment%></p>
<%end%>

<br><br>

app/views/reviews/create.js.erb
$('#comment-form').html("<%=j render partial:'comment_form',locals:{review:@review}%>");

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<% content_for :title, "All Reviews" %>
<div class="container">
      <div class="row">
        <div class="col-lg-1 col-md-1"></div>
        <div class="col-lg-10 col-md-10">
          <%=render @reviews%>
        </div>
        <div class="col-lg-1 col-md-1"></div>
      </div>
</div>

<script type="text/javascript">
$('.raty').each(function(){

    var tid = $(this).attr('ref'); 
    var score  = $(this).attr('score-helper');
    console.log(tid);
    $(this).raty({
          path:"/assets",
          target : tid ,
          readOnly:  true,
          score:score,
          number:     10,
          showHalf:  true
    }); 
}); 

</script>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/update.js.erb
alert('Your comment has been added!');
$('#reviews').prepend('<%=j render partial:"reviews/review",locals:{review:@review}%>');

$('#raty-<%=@review.id%>').raty({
          path:"/assets",
          readOnly:  true,
          score:<%=@review.rating%>,
          number:     10,
          showHalf:  true
}); 